src/pymatching/bindings.cpp, src/pymatching/lemon_mwpm.cpp, src/pymatching/lemon_mwpm.h, src/pymatching/matching.py, tests/test_matching.py
Adds `BlossomFailureException` which is thrown when `lemon::MaxWeightedPerfectMatching` fails to solve the matching problem, preventing a segmentation fault. If a `BlossomFailureException` is thrown when local matching is used, it is caught by `pymatching.matching._local_matching`, which increases `num_neighbours` and retries decoding. If multiple attempts of this fail, the `BlossomFailureException` is re-raised.
Fixes #11
=> Prevent Python interpreter from crashing when the blossom algorithm fails

.github/workflows/wheels.yml
Fix issue #24 by updating the pybind11 submodule and adding python 3.10 windows builds back into the CI
=> Fix win32 python310

src/pymatching/sparse_blossom/driver/mwpm_decoding.cc, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.test.cc, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/flooder/graph.h, tests/matching/decode_test.py
Fixes an issue where adding a detection event on a node marked as a boundary node in the Python API led to:
```
ValueError: No perfect matching could be found. This likely means that the syndrome has odd parity in the support of a connected component without a boundary.
```
E.g. This breaks tests in qiskit-qec: https://github.com/qiskit-community/qiskit-qec/issues/276
The fix is just to zero out the syndrome in the support of these boundary nodes, since the algorithm already handles the boundary correctly without these additional detection events.
=> Zero out syndrome in the support of UserGraph boundary nodes

README.md, src/pymatching/matching.py, src/pymatching/sparse_blossom/driver/mwpm_decoding.cc, src/pymatching/sparse_blossom/driver/user_graph.pybind.cc, tests/matching/decode_test.py, tests/matching/docstrings_test.py
Fixes #32. Adds `pymatching.Matching.decode_batch`, with options to load from bit-packed (or not) shots numpy arrays, and return bit-packed (or not) predictions numpy arrays. Faster than looping over `Matching.decode` in Python, especially for small problems sizes or low p. E.g. when decoding d=11, p=0.1% surface code circuits, looping over `Matching.decode` is 1us per round vs 0.37us per round using `Matching.decode_batch`. For d=5, p=0.01%, looping `Matching.decode` in python is 0.8us per round vs 0.02us per round with `Matching.decode_batch`.
=> Added method Matching.decode_batch

docs/toric-code-example.ipynb
actual_logical_flipped is determined by noise, not by the prediction. Fixed this one line in the documentation.
=> Fixed typo in toric code documentation

src/pymatching/sparse_blossom/driver/io.h
Perhaps this `pm::MatchingGraph` construction was left in by accident from a previous implementation of `iter_discretized_edges`. It has no effect here so may as well remove it.
=> Remove unnecessary line from driver/io.h

.gitignore, BUILD, CMakeLists.txt, WORKSPACE, setup.py, src/pymatching/sparse_blossom/diagram/animation_main.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.perf.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.test.cc, src/pymatching/sparse_blossom/driver/namespaced_main.cc, src/pymatching/sparse_blossom/flooder/detector_node.h, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/search/search_flooder.test.cc
- Add a `libpymatching` target to the CMakeLists.txt file
- Add support for building with bazel
- Add a `WORKSPACE` file
- Add a `BUILD` file
- Try it with `bazel build :all`
- Add an `IF(EXISTS ${CMAKE_CURRENT_LIST_DIR}/pybind11/CMakeLists.txt)` around the pybind11 cmake target
- Also included a warning message that explains how to fix the issue
- This avoids some issues where cmake fetching a project won't recursively fetch the submodules, preventing everything from working instead of just the pybind11 target
- Also it avoids some potential getting-started issues, or at least defers them, with getting the code to build
- Fix some constructor order warnings in `DetectorNode` and `MatchingGraph`
- Fix some implicit downcast warnings
- Bump the stim commit tag to the latest one on main, …
=> Make it easier to use pymatching as a C++ dependency

.gitignore, src/pymatching/sparse_blossom/ints.h
- Have to include `<cstdint>` to get types like uint64_t
=> Fix build failing when using gcc 13

.github/workflows/ci.yml, .gitignore, README.md, setup.py, src/pymatching/matching.py, tests/matching/load_from_rustworkx_test.py, tests/matching/output_graph_test.py, tests/matching/properties_test.py, tests/matching/retworkx_test.py
Rename retworkx to rustworkx. Methods `Matching.load_from_rustworkx` and `Matching.to_rustworkx` are added, a `DeprecationWarning` has been added to `Matching.load_from_retworkx` and `Matching.to_retworkx`. Fixes #62.
=> Retworkx to rustworkx

.github/workflows/ci.yml, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, tests/matching/decode_test.py
When converting from a pm::UserGraph to a pm::MatchingGraph or pm::SearchGraph, all boundary nodes in the pm::UserGraph are merged into one virtual boundary node. This can sometimes lead to parallel boundary edges during the conversion. Previously, when these parallel boundary edges arose, only the first-added boundary edge was kept, leading to issue #81. This PR fixes the issue by keeping only the minimum-weight parallel boundary edge, since this edge is guaranteed to be chosen over the others by blossom.
Fixes #81.
=> Keep minimum weight edge when merging parallel boundary edges in conversion from UserGraph to MatchingGraph/SearchGraph

.readthedocs.yaml
See: https://blog.readthedocs.com/drop-support-system-packages/
=> Removes python.system_packages from .readthedocs.yaml

.github/workflows/ci.yml, tests/matching/load_from_check_matrix_test.py
As of scipy 1.13 loading a scipy.sparse matrix with an invalid input type can now raise a ValueError instead of a TypeError. Therefore this PR modifies the PyMatching tests to test that scipy taises either a TypeError or ValueError, rather than just the former. Most of the diff is just from running a formatter. This PR also removes the unnecessary universal2 wheels from cibuildwheel.
=> Test for either ValueError or TypeError when loading scipy.sparse

.github/workflows/ci.yml, CMakeLists.txt, data/tagged_circuit.stim, data/tagged_dem.dem, docs/sphinx_docs/requirements.txt, setup.py, src/pymatching/matching.py, src/pymatching/sparse_blossom/driver/mwpm_decoding.perf.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.test.cc, tests/matching/load_from_stim_test.py
This PR:
* Adds support for Numpy v2
* Includes pre-built binaries for Python v3.13
* Adds support for loading stim circuits and DEMs with tags by bumping the stim C++ dependency version
* Adds minor API improvements (e.g. supporting pathlib.Path)
* Removes pre-built binaries for Python 3.7 on macos
=> Support Numpy v2 and update dependencies

.github/workflows/ci.yml
CI was breaking due to [this issue](https://github.com/python-pillow/Pillow/issues/9057) (earlier cibuildwheel versions have a different default manylinux image so pillow binary wheels weren't available). Updating to cibuildwheel v3.0.0 should fix this.
=> Update cibuildwheel to v3.0.0

CMakeLists.txt, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.test.cc
This PR introduces `iter_dem_instructions_include_correlations`, a helper method that iterates through `error` instructions in the DEM and processes components of a suggested decomposition (with fewer than 3 detectors) of a hyper edge as per a user-provided handler. In a future PR, this method will be used to capture information about correlations between decomposed error mechanisms.
It also re-adds in tests for `merge_weights` that were removed erroneously in a prior change.
We also establish a baseline for loading a DEM with correlated information included:
```
[.................*<<|....................] 530 us (vs 290 us) (2.8 Mdets/s) (9.5 Mlayers/s) (1.9 Mshots/s) Decode_surface_r5_d5_p1000
[................*<<<|....................]  23 ms (vs  10 ms) (920 kdets/s) ( 59 klayers/s) …
```
=> Add method to iterate through a DEM which decomposes Hyper Edges

src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.test.cc
Conversion to a user graph with correlations turned on will now throw an exception when:
- An edge decomposition contains a hyperedge
- An edge with probability greater than 0.5 is present in the DEM (we don't support negative edge weights for correlated matching yet).
=> Add constraints on DEM validity for correlated matching.

src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.test.cc
This PR extends `iter_dem_instructions_include_correlations` to track the joint probabilities between components that arise from the same error instruction.
The core of this change is the introduction of a `joint_probabilities map` which is populated during the DEM iteration. This map stores the probability of any two error components occurring together.
All existing tests have been updated to pass in the joint_probabilities map and verify its final state.
-- Performance before this PR -- 
```
[.................*<<|....................] 530 us (vs 290 us) (2.8 Mdets/s) (9.5 Mlayers/s) (1.9 Mshots/s) Decode_surface_r5_d5_p1000
[................*<<<|....................]  23 ms (vs  10 ms) (930 kdets/s) ( 59 klayers/s) (5.3 kshots/s) Decode_surface_r11_d11_p100 …
```
=> Track joint probabilities of correlated errors

src/pymatching/sparse_blossom/driver/implied_weights.h, src/pymatching/sparse_blossom/driver/mwpm_decoding.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.test.cc, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.pybind.cc, src/pymatching/sparse_blossom/driver/user_graph.test.cc, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/flooder/graph.h, src/pymatching/sparse_blossom/flooder/graph.test.cc, src/pymatching/sparse_blossom/flooder/graph_flooder.test.cc, src/pymatching/sparse_blossom/matcher/mwpm.test.cc, src/pymatching/sparse_blossom/search/search_flooder.test.cc, src/pymatching/sparse_blossom/search/search_graph.cc, src/pymatching/sparse_blossom/search/search_graph.h, src/pymatching/sparse_blossom/search/search_graph.test.cc
This PR fixes a bug where the old logic was assigning incorrectly computed weights to match graph edges. After this PR, edges on the graph are correctly normalized and weighted.
=> Fix edge reweighting logic

src/pymatching/matching.py, src/pymatching/sparse_blossom/driver/implied_weights.h, src/pymatching/sparse_blossom/driver/mwpm_decoding.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.h, src/pymatching/sparse_blossom/driver/mwpm_decoding.perf.cc, src/pymatching/sparse_blossom/driver/mwpm_decoding.test.cc, src/pymatching/sparse_blossom/driver/namespaced_main.cc, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.pybind.cc, src/pymatching/sparse_blossom/driver/user_graph.test.cc, src/pymatching/sparse_blossom/flooder/detector_node.h, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/flooder/graph.h, src/pymatching/sparse_blossom/flooder/graph.test.cc, src/pymatching/sparse_blossom/flooder/graph_flooder.test.cc, src/pymatching/sparse_blossom/matcher/mwpm.test.cc, src/pymatching/sparse_blossom/search/search_detector_node.h, src/pymatching/sparse_blossom/search/search_flooder.test.cc, src/pymatching/sparse_blossom/search/search_graph.cc, src/pymatching/sparse_blossom/search/search_graph.h, src/pymatching/sparse_blossom/search/search_graph.test.cc, tests/matching/decode_test.py
This PR implements the logic to store conditional edge weights
* `UserEdge` Struct: Added a implied_weights_for_other_edges vector to store re-weighting rules for other edges when this edge is part of an error.
* `populate_implied_edge_weights`: Implemented the function to calculate conditional probabilities and populate the new vector.
* Testing: Added a new unit test (UserGraph.PopulateImpliedEdgeWeights) to verify the correctness of the new logic.
Performance before this PR:
```
[.................*<<|....................] 530 us (vs 290 us) (2.8 Mdets/s) (9.6 Mlayers/s) (1.9 Mshots/s) Decode_surface_r5_d5_p1000
[................*<<<|....................]  23 ms (vs  10 ms) (930 kdets/s) ( 59 klayers/s) (5.4 kshots/s) Decode_surface_r11_d11_p100 …
```
=> Populate implied edge weights in edges in the User Graph

src/pymatching/sparse_blossom/driver/mwpm_decoding.test.cc, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/flooder/graph.h, src/pymatching/sparse_blossom/flooder/graph.test.cc, src/pymatching/sparse_blossom/flooder/graph_flooder.test.cc, src/pymatching/sparse_blossom/matcher/mwpm.test.cc, src/pymatching/sparse_blossom/search/search_flooder.test.cc, src/pymatching/sparse_blossom/search/search_graph.cc, src/pymatching/sparse_blossom/search/search_graph.h, src/pymatching/sparse_blossom/search/search_graph.test.cc
Fixes https://github.com/oscarhiggott/PyMatching/issues/145 and https://github.com/oscarhiggott/PyMatching/issues/150
=> Make previously free edges to implied weights unconverted variable a class member

src/pymatching/matching.py, src/pymatching/sparse_blossom/driver/mwpm_decoding.perf.cc, src/pymatching/sparse_blossom/driver/user_graph.cc, src/pymatching/sparse_blossom/driver/user_graph.h, src/pymatching/sparse_blossom/driver/user_graph.perf.cc, src/pymatching/sparse_blossom/driver/user_graph.test.cc, src/pymatching/sparse_blossom/flooder/graph.cc, src/pymatching/sparse_blossom/flooder/graph.h, tests/matching/decode_test.py
Checks that the user has set enable_correlations=True when loading from a stim circuit or dem if the user decodes with enable_correlations=True
Also checks that the user has set decompose_errors=True when generating a dem when they try to load with enable_correlations=True
In both cases a ValueError is raised.
Tests added to check for the ValueError.
=> Check for invalid pymatching.Matching configuration when decoding with enable_correlations=True

setup.py
This should cause the license metadata to be populated in pypi to be available for other tools.
=> Include license information in setup.py
